"""Optional Stable Diffusion 1.5 sidecar.

The diffusion engine is deliberately separate from ``model_module.ModelManager``.
This keeps the existing PyTorch/llama.cpp LLM paths and their worker contracts
unchanged while the SD 1.5 local path is validated.
"""

from .artifacts import DiffusionArtifact, DiffusionArtifactInspector
from .assets import (
    ASSET_CATALOG,
    DiffusionAssetManager,
    DiffusionAssetSpec,
    IP_ADAPTER_REPO,
    IP_ADAPTER_REVISION,
    INPAINT_REPO,
    INPAINT_REVISION,
    INSTRUCTION_REPO,
    INSTRUCTION_REVISION,
    LOCAL_PROXY_FALLBACK,
    get_asset_spec,
    verify_asset_directory,
)
from .presets import DiffusionPreset, get_preset, list_presets
from .distributed import (
    BlobAuthorizationError,
    BlobConflict,
    BlobLease,
    BlobNotFound,
    BlobTransferTokenSigner,
    BlobUploadSession,
    BlobValidationError,
    DistributedBlobError,
    DiffusionArtifactComponent,
    DiffusionArtifactManifest,
    PersistentBlobDescriptor,
    PersistentImageBlobStore,
)
from .data_plane import (
    DATA_PLANE_PREFIX,
    MAX_TRANSFER_CHUNK_BYTES,
    DiffusionDataPlaneRuntime,
)
from .worker_adapter import (
    IMAGE_PROTOCOL_VERSION,
    DiffusionCoordinatorControlPlane,
    DiffusionExecutionResult,
    DiffusionInputTransferPlanBuilder,
    DiffusionResultIngestor,
    DiffusionWorkerAdapter,
    remote_diffusion_provider_id,
    RemoteDiffusionProvider,
)
from .worker_runtime import DiffusionWorkerRuntime, DiffusionWorkerRuntimeError
from .coordinator_runtime import DiffusionCoordinatorRuntime
from .transfer import (
    DiffusionBlobTransferClient,
    DiffusionTransferError,
    TransferRequester,
    TransferResponse,
)
from .sd15_engine import (
    GenerationCancelled,
    SD15Engine,
    SD15EngineConfig,
    SD15GenerationRequest,
    SD15GenerationResult,
)
from .service import (
    DiffusionConflictError,
    DiffusionBlobInUseError,
    DiffusionBlobReferencedError,
    DiffusionInputError,
    DiffusionNotFoundError,
    DiffusionService,
    DiffusionServiceError,
    DiffusionUnsupportedError,
    DIFFUSION_MAX_IMAGE_PIXELS,
    DIFFUSION_MAX_UPLOAD_BYTES,
    ImageBlob,
    MemoryImageBlobStore,
    SD15EditRequest,
    SD15_LOAD_PROFILES,
    build_sd15_engine_config,
    build_sd15_generation_request,
)

__all__ = [
    "DiffusionArtifact",
    "DiffusionArtifactInspector",
    "DiffusionAssetManager",
    "DiffusionAssetSpec",
    "DiffusionConflictError",
    "DiffusionBlobInUseError",
    "DiffusionBlobReferencedError",
    "DiffusionInputError",
    "DiffusionNotFoundError",
    "DiffusionPreset",
    "DiffusionService",
    "DiffusionServiceError",
    "DiffusionUnsupportedError",
    "DistributedBlobError",
    "DiffusionArtifactComponent",
    "DiffusionArtifactManifest",
    "DIFFUSION_MAX_IMAGE_PIXELS",
    "DIFFUSION_MAX_UPLOAD_BYTES",
    "GenerationCancelled",
    "BlobAuthorizationError",
    "BlobConflict",
    "BlobLease",
    "BlobNotFound",
    "BlobTransferTokenSigner",
    "BlobUploadSession",
    "BlobValidationError",
    "PersistentBlobDescriptor",
    "PersistentImageBlobStore",
    "DATA_PLANE_PREFIX",
    "MAX_TRANSFER_CHUNK_BYTES",
    "DiffusionDataPlaneRuntime",
    "DiffusionCoordinatorControlPlane",
    "DiffusionExecutionResult",
    "DiffusionInputTransferPlanBuilder",
    "DiffusionResultIngestor",
    "DiffusionWorkerAdapter",
    "IMAGE_PROTOCOL_VERSION",
    "remote_diffusion_provider_id",
    "RemoteDiffusionProvider",
    "DiffusionWorkerRuntime",
    "DiffusionWorkerRuntimeError",
    "DiffusionCoordinatorRuntime",
    "DiffusionBlobTransferClient",
    "DiffusionTransferError",
    "TransferRequester",
    "TransferResponse",
    "SD15Engine",
    "SD15EngineConfig",
    "SD15GenerationRequest",
    "SD15GenerationResult",
    "ASSET_CATALOG",
    "IP_ADAPTER_REPO",
    "IP_ADAPTER_REVISION",
    "INPAINT_REPO",
    "INPAINT_REVISION",
    "INSTRUCTION_REPO",
    "INSTRUCTION_REVISION",
    "LOCAL_PROXY_FALLBACK",
    "MemoryImageBlobStore",
    "ImageBlob",
    "SD15EditRequest",
    "SD15_LOAD_PROFILES",
    "build_sd15_engine_config",
    "build_sd15_generation_request",
    "get_preset",
    "get_asset_spec",
    "list_presets",
    "verify_asset_directory",
]
