package com.qlh.inference.ui.theme

import androidx.compose.ui.graphics.Color

// ================================================================
// QLH 配色 — 中性黑白 Material 3 体系
// 浅色为白底黑字，深色为黑底白字；状态色不承担主题主色职责。
// ================================================================

// ---- 浅色主题 ----
val PrimaryLight = Color(0xFF151515)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFE9E9E9)
val OnPrimaryContainerLight = Color(0xFF171717)
val SecondaryLight = Color(0xFF4B4B4B)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFE5E5E5)
val OnSecondaryContainerLight = Color(0xFF222222)
val TertiaryLight = Color(0xFF353535)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFEEEEEE)
val OnTertiaryContainerLight = Color(0xFF202020)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFFFFFFF)
val OnBackgroundLight = Color(0xFF151515)
val SurfaceLight = Color(0xFFFFFFFF)
val OnSurfaceLight = Color(0xFF151515)
val SurfaceVariantLight = Color(0xFFE8E8E8)
val OnSurfaceVariantLight = Color(0xFF454545)
val OutlineLight = Color(0xFF767676)
val OutlineVariantLight = Color(0xFFC6C6C6)
val InverseSurfaceLight = Color(0xFF202020)
val InverseOnSurfaceLight = Color(0xFFF5F5F5)
val InversePrimaryLight = Color(0xFFF5F5F5)
val SurfaceDimLight = Color(0xFFDBDBDB)
val SurfaceBrightLight = Color(0xFFFFFFFF)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFF7F7F7)
val SurfaceContainerLight = Color(0xFFF2F2F2)
val SurfaceContainerHighLight = Color(0xFFECECEC)
val SurfaceContainerHighestLight = Color(0xFFE5E5E5)

// ---- 深色主题 ----
val PrimaryDark = Color(0xFFF3F3F3)
val OnPrimaryDark = Color(0xFF101010)
val PrimaryContainerDark = Color(0xFF303030)
val OnPrimaryContainerDark = Color(0xFFF4F4F4)
val SecondaryDark = Color(0xFFC9C9C9)
val OnSecondaryDark = Color(0xFF222222)
val SecondaryContainerDark = Color(0xFF303030)
val OnSecondaryContainerDark = Color(0xFFE8E8E8)
val TertiaryDark = Color(0xFFE5E5E5)
val OnTertiaryDark = Color(0xFF222222)
val TertiaryContainerDark = Color(0xFF262626)
val OnTertiaryContainerDark = Color(0xFFECECEC)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF000000)
val OnBackgroundDark = Color(0xFFF5F5F5)
val SurfaceDark = Color(0xFF080808)
val OnSurfaceDark = Color(0xFFF5F5F5)
val SurfaceVariantDark = Color(0xFF2B2B2B)
val OnSurfaceVariantDark = Color(0xFFC6C6C6)
val OutlineDark = Color(0xFF969696)
val OutlineVariantDark = Color(0xFF3D3D3D)
val InverseSurfaceDark = Color(0xFFE5E5E5)
val InverseOnSurfaceDark = Color(0xFF202020)
val InversePrimaryDark = Color(0xFF202020)
val SurfaceDimDark = Color(0xFF000000)
val SurfaceBrightDark = Color(0xFF222222)
val SurfaceContainerLowestDark = Color(0xFF050505)
val SurfaceContainerLowDark = Color(0xFF0D0D0D)
val SurfaceContainerDark = Color(0xFF121212)
val SurfaceContainerHighDark = Color(0xFF1A1A1A)
val SurfaceContainerHighestDark = Color(0xFF242424)

// ---- 语义色（状态提示用） ----
val SuccessGreen = Color(0xFF2E7D32)
val SuccessGreenDark = Color(0xFF81C784)
val WarningOrange = Color(0xFFEF6C00)
